#pragma once


//OBJECT TYPE ID
#define OBJECT_TYPE_GHOST	13


//PROPERTIES STATE VALUE
#define GHOST_FLYING_SPEED	0.048f
#define GHOST_FLYING_DELTAVX	0.001f
#define GHOST_FLYING_MAXVY	0.025f
#define GHOST_SPACE_TO_ACTIVE 100

//PROPERTIES
#define GHOST_HP	2
#define GHOST_ATK	2
#define GHOST_EXP 300

//WIDTH & HEIGHT
#define GHOST_WIDTH		28
#define GHOST_HEIGHT	28