#pragma once
//OBJECT TYPE ID
#define OBJECT_TYPE_PHANTOM_BAT	21



//WIDTH & HEIGHT
#define PHANTOMBAT_WIDTH			65
#define PHANTOMBAT_HEIGHT			32
#define PHANTOMBAT_TRANSPARENT_SPACE 16								//Dời 16px về bên phải để giảm độ dài cánh của Phantombat khi xét va chạm với simon


//STATE ID
#define PHANTOMBAT_FLY_STATE_NOT_SET -1
#define PHANTOMBAT_FLY_STATE_BEGIN 0
#define PHANTOMBAT_FLY_STATE_ATTACK 1
#define PHANTOMBAT_FLY_STATE_GOBACK 2



//COORDINATE TARGET
//ORIGINAL COORDINATE 
#define ORIGINAL_COORDNINATE_X 1296
#define ORIGINAL_COORDNINATE_Y 98


//FLYING TYPE 1
#define SFTYPE1_STATE_BEGIN_Y 203
#define SFTYPE1_STATE_BEGIN_X 1234

#define SFTYPE1_STATE_ATTACK_KIND1_Y 480 
#define SFTYPE1_STATE_ATTACK_KIND1_X 995 
#define SFTYPE1_STATE_ATTACK_KIND2_Y 500 
#define SFTYPE1_STATE_ATTACK_KIND2_X 1480 
#define SFTYPE1_STATE_ATTACK_KIND3_Y 350 
#define SFTYPE1_STATE_ATTACK_KIND3_X 1480 


//FLYING TYPE 2
#define SFTYPE2_STATE_BEGIN_KIND1_Y 160
#define SFTYPE2_STATE_BEGIN_KIND1_X 1378 
#define SFTYPE2_STATE_BEGIN_KIND2_Y 199
#define SFTYPE2_STATE_BEGIN_KIND2_X 1036 

#define SFTYPE2_STATE_ATTACK_KIND1_Y 480
#define SFTYPE2_STATE_ATTACK_KIND1_X 995 
#define SFTYPE2_STATE_ATTACK_KIND2_Y 350
#define SFTYPE2_STATE_ATTACK_KIND2_X 1480 



//STATE HIT SIMON
#define PHANTOMBAT_FLY_STATE_LEFT 1
#define PHANTOMBAT_FLY_STATE_RIGHT_TOP 2
#define PHANTOMBAT_FLY_STATE_RIGHT_BOTTOM 3


//SIMON COORDINATE LIMIT
#define PB_STATE_LEFT	1279
#define PB_STATE_TOP 229



//VELOCITY
#define PHANTOMBAT_VELOCITY_FALLDOWN 0.0005f




//PROPERTIES STATE VALUE
#define PHANTOMBAT_DISTANCE_ACTIVE 200



//TIME
#define PHANTOMBAT_TIME_WAITING 1500
#define PHANTOMBAT_TIME_FLYING 1000
#define DISAPPEAR_TIME_BOSS		1800			//Thời gian cho hiệu ứng biến mất của Boss

//PROPERTIES
#define PHANTOMBAT_HP	16 
#define PHANTOMBAT_ATK	2
#define PHANTOMBAT_EXP 3000


