#pragma once

//OBJECT TYPE ID
#define OBJECT_TYPE_WHITE_SKELETON	15
#define OBJECT_TYPE_BONE	16


//WIDTH & HEIGHT
#define WHITE_SKELETON_WIDTH			32
#define WHITE_SKELETON_HEIGHT			64


//JUMPING STATE
#define WHITE_SKELETON_NO_JUMP 0
#define WHITE_SKELETON_MIDDLE_JUMP 1
#define WHITE_SKELETON_FINAL_JUMP 2


//PROPERTIES STATE VALUE
#define WHITE_SKELETON_DELTA_VX			0.002f
#define WHITE_SKELETON_MAX_VX 0.04f

#define WHITE_SKELETON_JUMPING_FORWARD_SPEED 0.15f
#define WHITE_SKELETON_JUMPING_BACK_SPEED 0.14f
#define WHITE_SKELETON_JUMPING_UP_SPEED 0.35f

#define WHITE_SKELETON_GRAVITY 0.001f

#define WHITE_SKELETON_NEXT_JUMP_TIME 1000





//PROPERTIES
#define WHITE_SKELETON_HP	1 
#define WHITE_SKELETON_ATK	3
#define WHITE_SKELETON_EXP	300