#pragma once

//OBJECT TYPE ID
#define OBJECT_TYPE_HUNCH_BACK	14


//WIDTH & HEIGHT
#define HUNCH_BACK_WIDTH	32
#define HUNCH_BACK_HEIGHT	32


//PROPERTIES STATE VALUE
#define HUNCH_BACK_SPACE_TO_ACTIVE	153
#define HUNCH_BACK_WALKING_SPEED	0.2f
#define HUNCH_BACK_JUMPING_SPEED	0.4f
#define HUNCH_BACK_GRAVITY	0.002f

//PROPERTIES 
#define HUNCH_BACK_HP	1
#define HUNCH_BACK_ATK	3
#define HUNCH_BACK_EXP 500

//TIMER
#define HUNCH_BACK_TIME_TO_JUMP 2000