#pragma once


//GENERAL READER FILE DEFINITION
#define MAX_GAME_LINE 1024
#define GAME_FILE_SECTION_UNKNOWN -1





//SCENE MANAGER READER DEFINITION
#define GAME_FILE_SECTION_SETTINGS 1
#define GAME_FILE_SECTION_SCENES 2
#define GAME_FILE_SECTION_DATAPATH 3
#define GAME_FILE_SECTION_CAMERA 4
#define GAME_FILE_SECTION_SIMON 5




//SCENE READER DEFINITION
#define SCENE_SECTION_MAPSIZE 1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6



//SOUND READER DEFINITION
#define GAME_SOUND_TRACK 1
#define GAME_SOUND_EFFECT 2