#pragma once

//ID COMPONENT IN HUD
#define HUD_HP_PLAYER_ID	1
#define HUD_HP_PLAYER_LOSE_ID		2

#define HUD_FRAME_ID	4
#define HUD_SUBWEAPON_ID	5
#define HUD_ITEM_ID		6



//BREAK SECTION
#define HUD_TEXTURE	1
#define HUD_SPRITE	2
#define HUD_HP	3
#define HUD_ITEM	4


//CONST FOR HUD PRESENT
#define HP_SIZE	16

#define HUD_TEXT_SCORE_LEN	6
#define HUD_TEXT_TIME_LEN	4
#define HUD_TEXT_IDSCENE_LEN	2
#define HUD_TEXT_SUBWEAPONCOUNTER_LEN	2
#define HUD_TEXT_LIVE_LEN	2


//FONT REGION
#define HUD_LEFT	0
#define HUD_TOP	15
#define HUD_BOTTOM	80
#define HUD_RIGHT	512


//POSITION
#define SUBWEAPON_FRAME_X	288
#define SUBWEAPON_FRAME_Y	32

#define SUBWEAPON_INSIDE_X	305
#define SUBWEAPON_INSIDE_Y	38

#define ITEM_HUD_X	450
#define ITEM_HUD_Y	38

#define HP_PLAYER_POSITION_Y	31
#define HP_PLAYER_POSITION_X	105
#define HP_PLAYER_POSITION_X_SPACE	9
