#pragma once

//OBJECT TYPE ID
#define OBJECT_TYPE_BLACKKNIGHT	6

//WIDTH & HEIGHT
#define BLACKKNIGHT_WIDTH			32
#define BLACKKNIGHT_HEIGHT			64


//PROPERTIES STATE VALUE
#define BLACKKNIGHT_WALKING_SPEED		0.085f
#define BLACKKNIGHT_GRAVITY				0.001f

//REGION CHANGE BLACKNIGHT ORIENTATION
#define BN_REGION_CO_X 80
#define BN_REGION_CO_Y 20


//PROPERTIES
#define BLACKKNIGHT_HP	2 
#define BLACKKNIGHT_ATK	2
#define BLACKKNIGHT_EXP	400
