#pragma once


#define SOUND_FIGHTING_BOSS 7

#define SOUND_WHOPPING 10


#define ATTACK_TO_OBJECT 11

#define BROKEN_BRICK 12
#define SOUND_SHOW_HIDDEN_ITEM 13

#define SOUND_TOUCH_ITEM 14
#define SOUND_TOUCH_SUBWEAPON_ITEM 15

#define SOUND_ROSARY_EFFECT 16

#define SOUND_SIMON_PUSHED 17

#define SOUND_SW_STOP_WATCH 18
#define SOUND_SW_AXE 19
#define SOUND_SW_DAGGER 20
#define SOUND_SW_BOOMERANG 21
#define SOUND_SW_HOLYWATER 22



#define SOUND_INVISIBLE_START 23
#define SOUND_INVISIBLE_END 24

#define SOUND_FINISH_GAME 25

#define SOUND_SCORE_BY_TIMEREMAIN 26
#define SOUND_SCORE_BY_SMALLHEART 27

#define SOUND_SIMON_DEAD 28