#pragma once
//OBJECT TYPE ID
#define OBJECT_TYPE_CANDLE	7


//TORCH STATE ID
#define CANDLE_ACTIVE		0
#define CANDLE_DESTROYED	1


#define CANDLE 0


//	WIDTH & HEIGHT
#define CANDLE_ACTIVE_WIDTH			16
#define CANDLE_ACTIVE_HEIGHT			32