 #pragma once

// OBJECT TYPE ID
#define OBJECT_TYPE_ITEMS				2


//TYPE ITEMS
#define NORMAL_ITEMS	1
#define SPECIAL_ITEMS	2
#define PERMANENT_ITEMS	3


// ITEM TYPE ID
//NORMAL ITEMS
#define ITEM_MORNINGSTAR			0
#define ITEM_SMALLHEART		1
#define ITEM_BIGHEART		2
#define ITEM_MONEYBAG_RED	3
#define ITEM_MONEYBAG_PURPLE	4
#define ITEM_MONEYBAG_WHITE   5


//SPECIAL ITEMS
#define ITEM_ROSARY			6
#define ITEM_INVISIBILITYPOTION	7
#define ITEM_DOUBLESHOT		8
#define ITEM_TRIPLESHOT		9


//HIDDEN ITEMS
#define ITEM_PORKCHOP		10
#define ITEM_MONEYBAG 11
#define ITEM_CHEST    12
#define ITEM_DIADEM   13

//WEAPON ITEMS
#define ITEM_DAGGER			14
#define	ITEM_AXE				15
#define ITEM_HOLYWATER		16
#define ITEM_BOOMERANG		17
#define	ITEM_STOPWATCH		18


//HUD
#define DAGGER_HUD			0
#define	AXE_HUD			    1
#define HOLY_WATER_HUD		2
#define BOOMERANG_HUD		3
#define	STOP_WATCH_HUD		4






//ITEM PROPERTIES
#define ITEM_FALLING_Y			0.15f
#define ITEM_TIME_DISAPEAR		5000
