#pragma once


//OBJECT TYPE ID
#define OBJECT_TYPE_VAMPIREBAT	10



//WIDTH & HEIGHT
#define VAMPIRE_BAT_WIDTH			32
#define VAMPIRE_BAT_HEIGHT			32



//PROPERTIES STATE VALUE
#define VAMPIRE_BAT_FLYING_SPEED	0.2f
#define VAMPIRE_BAT_MAX_VY	0.2f
#define VAMPIRE_BAT_SPEED_VARIATION 0.004f
#define VAMPIRE_BAT_DELTA_VY 0.009f




//PROPERTIES
#define VAMPIREBAT_HP	1 
#define VAMPIREBAT_ATK	2
#define VAMPIREBAT_EXP 200


