#pragma once

//OBJECT TYPE ID
#define OBJECT_TYPE_SOLIDER	6

//WIDTH & HEIGHT
#define SOLIDER_WIDTH			32
#define SOLIDER_HEIGHT			64


//STATE ID
#define SOLIDER_WALKING		0
#define SOLIDER_DESTROYED	1

//PROPERTIES STATE VALUE
#define SOLIDER_WALKING_SPEED		0.04f
#define SOLIDER_GRAVITY				0.002f


//HP 
#define SOLIDER_HP	2 


//REGION
#define SOLIDER_REGION_LEFT	65
#define SOLIDER_REGION_RIGHT	290