#pragma once
//OBJECT TYPE ID
#define OBJECT_TYPE_MORNINGSTAR	1


// WIDTH & HEIGHT
#define MORNINGSTAR_LEVEL1_2_WIDTH				42
#define MORNINGSTAR_LEVEL3_WIDTH		78
#define MORNINGSTAR_HEIGHT			15

//BOUNDING BOX MOVING
#define MORNING_STAR_BB_MOVING_TOP 12
#define MORNING_STAR_BB_MOVING_LEFT 74





// MORNING STAR LEVEL ID
#define MS_LEVEL1		1
#define MS_LEVEL2		2
#define MS_LEVEL3		3


//DAMAGE
#define MS_DAMAGE	1